spring.application.name=VeterinariaHuellitas

# Puerto dinámico para Render (en local usará 8091)
server.port=${PORT:8091}

# Conexión flexible a Aiven MySQL con SSL activado
spring.datasource.url=${DB_URL:jdbc:mysql://mysql-3e35a-carloshuayaney84-bd9c.j.aivencloud.com:15087/defaultdb?sslMode=REQUIRED}
spring.datasource.username=${DB_USER:avnadmin}
spring.datasource.password=${DB_PASSWORD:AVNS_OdlB3uIQpBpziv2lpec}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuración JPA / Hibernate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true